#Lista de Palavras, têm de estar escritas com letra maiúscula
words = ["MORANGO","ARROZ","MASSA","BANANA","CENOURA","ALFACE","LARANJA","ESPARGUETE","BIFE","SARDINHA","ATUM","ERVILHAS","TOMATE","UVAS","MILHO","SOPA","DAMASCO","DIOSPIRO","CASTANHA",
"NATAS","BACALHAU","MELANCIA","MELOA","VINAGRE","AZEITE","KETCHUP","MAIONESE","MOSTARDA","SALSA","COENTRO","SAL"]